# Generated by Django 3.2.7 on 2021-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20211004_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Post', max_length=255),
        ),
    ]
