# Generated by Django 3.2.8 on 2021-10-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20211014_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catergory',
            new_name='category',
        ),
    ]
